---
# also reset these values before running the playbook
pull_secret_path: "/path/to/pull-secret.txt"
ssh_key_path: "/path/to/ssh-key.pub"
base_domain: "amirnajafiz.ir"
cluster_name: "your_cluster_name"
k8s_service_host: "api.your_cluster_name.amirnajafiz.ir"
k8s_service_port: 6443
keycloak_url: "keycloak.amirnajafiz.ir"
keycloak_realm: "your_realm"
keycloak_client_id: "your_client_id"
keycloak_client_secret: "your_client_secret"