---
- name: Download Cilium CLI
  get_url:
    url: https://github.com/cilium/cilium-cli/releases/latest/download/cilium-linux-amd64.tar.gz
    dest: /tmp/cilium-linux-amd64.tar.gz

- name: Extract Cilium CLI
  unarchive:
    src: /tmp/cilium-linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    creates: /usr/local/bin/cilium

- name: Install Cilium in the cluster
  command: >
    cilium install

- name: Enable Hubble (Cilium observability)
  command: >
    cilium hubble enable

- name: Enable Hubble UI
  command: >
    cilium hubble ui
