---
- name: Install OpenShift Container Platform
  hosts: all
  become: true
  tasks:
    - name: Install required packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - wget
        - git
        - vim
        - nano
        - iptables-services
        - bind-utils
        - iptables
        - ntp
        - ntpdate
        - yum-utils
        - device-mapper-persistent-data
        - lvm2

    - name: Enable required repositories
      yum_repository:
        name: "{{ item }}"
        description: "{{ item }}"
        file: "{{ item }}.repo"
        state: present
      with_items:
        - rhel-7-server-rpms
        - rhel-7-server-extras-rpms
        - rhel-7-server-ansible-2.9-rpms
        - rhel-7-server-ose-4.7-rpms
        - rhel-7-server-ansible-2.9-rpms

    - name: Install OpenShift prerequisites
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - NetworkManager
        - bash-completion
        - cockpit
        - cockpit-kubernetes
        - cockpit-ostree
        - device-mapper
        - glibc-langpack-en
        - pigz
        - python3
        - python3-pip
        - python3-setuptools
        - python3-virtualenv
        - rsync
        - tar
        - unzip
        - wget
        - podman
        - openssl
        - httpd-tools

    - name: Enable required services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - NetworkManager
        - chronyd

    - name: Disable swap
      command: swapoff -a
      ignore_errors: true

    - name: Disable SELinux
      selinux:
        state: disabled

    - name: Download OpenShift installer
      get_url:
        url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest-4.7/openshift-client-linux.tar.gz
        dest: /tmp/openshift-client-linux.tar.gz

    - name: Extract OpenShift installer
      unarchive:
        src: /tmp/openshift-client-linux.tar.gz
        dest: /usr/local/bin
        remote_src: yes
        creates: /usr/local/bin/oc

    - name: Download OpenShift install binaries
      get_url:
        url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest-4.7/openshift-install-linux.tar.gz
        dest: /tmp/openshift-install-linux.tar.gz

    - name: Extract OpenShift install binaries
      unarchive:
        src: /tmp/openshift-install-linux.tar.gz
        dest: /usr/local/bin
        remote_src: yes
        creates: /usr/local/bin/openshift-install

    - name: Create OpenShift install directory
      file:
        path: /root/ocp-install
        state: directory

    - name: Generate OpenShift install config
      command: >
        openshift-install create install-config
        --dir=/root/ocp-install
        --metadata='{"compute":[{"name":"master","replicas":1},{"name":"worker","replicas":1}]}' # Adjust replicas based on your requirements
        creates: /root/ocp-install/install-config.yaml

    - name: Install OpenShift cluster
      command: >
        openshift-install create cluster
        --dir=/root/ocp-install
        --log-level=info
      async: 0
      poll: 0
